"""Streamlit viewer for reports produced by agentic_ai.py.

This app makes NO LLM or market-data calls. It loads a pickle directly
from the root directory and renders it, so deployment needs no API key.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from report_io import list_reports, load_report

# Look for .pkl files directly in the main project folder instead of 'reports/'
REPORT_DIR = Path(__file__).parent


@st.cache_data(show_spinner=False)
def read_report(path_str: str, mtime: float) -> dict[str, Any]:
    """Cached on (path, mtime) so replacing a file invalidates the cache."""
    return load_report(path_str)


def label_for(path: Path) -> str:
    try:
        p = read_report(str(path), path.stat().st_mtime)
        return f"{', '.join(p['tickers'])} · {p['created_at'].replace('T', ' ')[:16]} UTC"
    except ValueError:
        return f"{path.name} (unreadable)"


def price_chart(prices: dict[str, dict[str, list]], period: str) -> go.Figure | None:
    fig = go.Figure()
    for ticker, series in prices.items():
        if not series.get("close"):
            continue
        base = series["close"][0]
        fig.add_trace(
            go.Scatter(
                x=pd.to_datetime(series["dates"]),
                y=[v / base * 100 for v in series["close"]],
                mode="lines",
                name=ticker,
            )
        )
    if not fig.data:
        return None
    fig.update_layout(
        title=f"Price performance, rebased to 100 ({period})",
        yaxis_title="Indexed price",
        height=420,
        margin={"l": 10, "r": 10, "t": 50, "b": 10},
    )
    return fig


def show_empty_state() -> None:
    st.info("No report pickle found in the project directory. Add your `.pkl` file to GitHub.")
    st.code(
        'python agentic_ai.py --tickers NVDA AMD '
        '--question "Compare growth, profitability and valuation"',
        language="bash",
    )


def main() -> None:
    st.set_page_config(page_title="Multi-Agent Financial Analyst", page_icon="📈", layout="wide")
    st.title("📈 Multi-Agent Financial Research Analyst")
    st.caption("Viewer for reports generated by `agentic_ai.py` (Planner → Data → Analyst → Critic). Educational only.")

    # Find all .pkl files directly in the root directory (excluding subfolders if any)
    paths = [p for p in REPORT_DIR.glob("*.pkl") if p.is_file()]
    if not paths:
        show_empty_state()
        return

    with st.sidebar:
        st.header("Report")
        path = st.selectbox("Select a report", paths, format_func=label_for)
        st.caption("Reports are pickle files created offline by the agent pipeline.")

    try:
        p = read_report(str(path), path.stat().st_mtime)
    except ValueError as exc:
        st.error(f"Could not load this report: {exc}")
        return

    st.markdown(f"**Question:** {p['question']}")
    st.caption(
        f"Tickers: {', '.join(p['tickers'])} · Window: {p['period']} · Model: {p['model']} · "
        f"Generated: {p['created_at'].replace('T', ' ')} UTC"
    )

    if p["passed"]:
        st.success(f"Critic passed after {p['revisions']} revision(s).")
    else:
        st.warning(
            f"Critic still has {len(p['issues'])} open issue(s) after {p['revisions']} revision(s). "
            "Treat unverified claims with caution."
        )

    tab_report, tab_chart, tab_evidence, tab_trace = st.tabs(["Report", "Chart", "Evidence", "Trace & cost"])

    with tab_report:
        st.markdown(p["report"])
        st.download_button("Download report (.md)", p["report"], "research_report.md", "text/markdown")
        if p["issues"]:
            with st.expander("Open critic issues"):
                st.dataframe(pd.DataFrame(p["issues"]), width="stretch")
        with st.expander("Research plan"):
            st.json(p["plan"])

    with tab_chart:
        fig = price_chart(p["prices"], p["period"])
        if fig:
            st.plotly_chart(fig, width="stretch")
        else:
            st.info("No price data stored in this report.")

    with tab_evidence:
        st.caption("Every [S#] citation in the report points to a row below.")
        rows = [
            {
                "ID": s["sid"],
                "Kind": s["kind"],
                "Ticker": s["ticker"],
                "Title": s["title"],
                "URL": s["url"],
                "Retrieved": s["retrieved"],
            }
            for s in p["sources"]
        ]
        st.dataframe(pd.DataFrame(rows), width="stretch")
        for s in p["sources"]:
            with st.expander(f"[{s['sid']}] {s['title']}"):
                st.write(s["content"])

    with tab_trace:
        tot = p["totals"]
        c1, c2, c3 = st.columns(3)
        c1.metric("Input tokens", f"{tot['tokens_in']:,}")
        c2.metric("Output tokens", f"{tot['tokens_out']:,}")
        c3.metric("Wall time (s)", tot["seconds"])
        st.dataframe(pd.DataFrame(p["trace"]), width="stretch")


if __name__ == "__main__":
    main()
